name: Axe Accessibility Test
on:
  push:
    branches: [main]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on https://cbrooksacs.github.io/accessiblity/
      - run: npm i chromedriver
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe https://cbrooksacs.github.io/accessiblity/ --exit
