name: Axe Accessibility Test
on:
  push:
    branches: [main]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - name: Run axe
        run:
          npm install npm@latest -g
          npm install @axe-core/cli -g
          axe https://cbrooksacs.github.io/accessiblity
          
          
    
