name: Axe Accessibility Test
on:
  push:
    branches: [main]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - name: Run axe
        run:
          npm i @axe-core/cli
          axe https://cbrooksacs.github.io/accessiblity/ --exit
          
          
    
