name: Axe Accessibility Test
on:
  push:
    branches: [main]

jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on https://cbrooksacs.github.io/accessiblity/
      - name: Run axe
        run: |
          npm install -g @axe-core/cli
          axe https://cbrooksacs.github.io/accessiblity/ --chromedriver-path="https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/mac-arm64/chrome-mac-arm64.zip" --exit
          
          
    
