name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Audit URLs using Lighthouse
       uses: treosh/lighthouse-ci-action@v7
       with:
         urls: https://cbrooksacs.github.io/accessiblity/
         uploadArtifacts: true # save results as an action artifacts
         temporaryPublicStorage: true # upload lighthouse audits to google temporary storage
