name: Lighthouse CI
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Audit URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        id: lighthouse
        with:
          urls: |
            https://cbrooksacs.github.io/accessiblity/
          temporaryPublicStorage: false # upload lighthouse report to the temporary storage
