name: Lighthouse
on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Audit URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        id: lighthouse
        with:
          urls: |
            https://cbrooksacs.github.io/accessiblity/
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
