name: Lighthouse
on: push
jobs:
  lighthouse:
    runs-on: ubuntu-latestt
    steps:
      - uses: actions/checkout@v3
      - name: Run Lighthouse on urls and validate with lighthouserc
        uses: treosh/lighthouse-ci-action@v10
        with:
          url: https://cbrooksacs.github.io/accessiblity/
