name: Lighthouse Check
on: push

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: treosh/lighthouse-ci-action@v3
      with:
        outputDirectory: /tmp/artifacts
        urls: 'https://cbrooksacs.github.io/accessiblity/'
    - name: Upload artifacts
      uses: actions/upload-artifact@master
      with:
        name: Lighthouse reports
        path: /tmp/artifacts
