name: pa11y
# on:
#   push:
#     branches: [main]

jobs:
  pa11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm start & npx wait-on https://cbrooksacs.github.io/accessiblity/
      - name: Run pa11y
        run: |
          npm install -g pa11y
          pa11y --runner axe --runner htmlcs https://cbrooksacs.github.io/accessiblity/ --timeout 500000 --ignore issue-code-1